name: Docker image push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build & Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ${{ secrets.REPOSITORY_DOCKER_HUB }}
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ sercrets.USERNAME_DOCKER_HUB }}
        password: ${{ sercrets. PASSWORD_DOCKER_HUB }}